export const SUN="🔆"
export const MOON="🌙"
export const ROOM="🙋🏻"
export const USERS="👥"
export const CHAT="💬"
export const TROPHY="🏆"
export const SHIELD="🛡️"
export const PLAY="▶︎"
export const X="🗙";
export const O="𝐎"
export const FLAG="🏳️"
export const DRAW="🤝"
export const CLOSE = "⤫";
